//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ShopMyPhamModel1", "FK_SanPhamHinh_SanPham", "SanPham", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(ShopMyPham.Models.SanPham), "SanPhamHinh", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ShopMyPham.Models.SanPhamHinh), true)]

#endregion

namespace ShopMyPham.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ShopMyPhamEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ShopMyPhamEntities1 object using the connection string found in the 'ShopMyPhamEntities1' section of the application configuration file.
        /// </summary>
        public ShopMyPhamEntities1() : base("name=ShopMyPhamEntities1", "ShopMyPhamEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShopMyPhamEntities1 object.
        /// </summary>
        public ShopMyPhamEntities1(string connectionString) : base(connectionString, "ShopMyPhamEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShopMyPhamEntities1 object.
        /// </summary>
        public ShopMyPhamEntities1(EntityConnection connection) : base(connection, "ShopMyPhamEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DonHang> DonHangs
        {
            get
            {
                if ((_DonHangs == null))
                {
                    _DonHangs = base.CreateObjectSet<DonHang>("DonHangs");
                }
                return _DonHangs;
            }
        }
        private ObjectSet<DonHang> _DonHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DonHangChiTiet> DonHangChiTiets
        {
            get
            {
                if ((_DonHangChiTiets == null))
                {
                    _DonHangChiTiets = base.CreateObjectSet<DonHangChiTiet>("DonHangChiTiets");
                }
                return _DonHangChiTiets;
            }
        }
        private ObjectSet<DonHangChiTiet> _DonHangChiTiets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhuyenMai> KhuyenMais
        {
            get
            {
                if ((_KhuyenMais == null))
                {
                    _KhuyenMais = base.CreateObjectSet<KhuyenMai>("KhuyenMais");
                }
                return _KhuyenMais;
            }
        }
        private ObjectSet<KhuyenMai> _KhuyenMais;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Loai> Loais
        {
            get
            {
                if ((_Loais == null))
                {
                    _Loais = base.CreateObjectSet<Loai>("Loais");
                }
                return _Loais;
            }
        }
        private ObjectSet<Loai> _Loais;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuanTri> QuanTris
        {
            get
            {
                if ((_QuanTris == null))
                {
                    _QuanTris = base.CreateObjectSet<QuanTri>("QuanTris");
                }
                return _QuanTris;
            }
        }
        private ObjectSet<QuanTri> _QuanTris;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SalePromotion> SalePromotions
        {
            get
            {
                if ((_SalePromotions == null))
                {
                    _SalePromotions = base.CreateObjectSet<SalePromotion>("SalePromotions");
                }
                return _SalePromotions;
            }
        }
        private ObjectSet<SalePromotion> _SalePromotions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SanPham> SanPhams
        {
            get
            {
                if ((_SanPhams == null))
                {
                    _SanPhams = base.CreateObjectSet<SanPham>("SanPhams");
                }
                return _SanPhams;
            }
        }
        private ObjectSet<SanPham> _SanPhams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SanPhamHinh> SanPhamHinhs
        {
            get
            {
                if ((_SanPhamHinhs == null))
                {
                    _SanPhamHinhs = base.CreateObjectSet<SanPhamHinh>("SanPhamHinhs");
                }
                return _SanPhamHinhs;
            }
        }
        private ObjectSet<SanPhamHinh> _SanPhamHinhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ThuongHieu> ThuongHieux
        {
            get
            {
                if ((_ThuongHieux == null))
                {
                    _ThuongHieux = base.CreateObjectSet<ThuongHieu>("ThuongHieux");
                }
                return _ThuongHieux;
            }
        }
        private ObjectSet<ThuongHieu> _ThuongHieux;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DonHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDonHangs(DonHang donHang)
        {
            base.AddObject("DonHangs", donHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DonHangChiTiets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDonHangChiTiets(DonHangChiTiet donHangChiTiet)
        {
            base.AddObject("DonHangChiTiets", donHangChiTiet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhuyenMais EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhuyenMais(KhuyenMai khuyenMai)
        {
            base.AddObject("KhuyenMais", khuyenMai);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Loais EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoais(Loai loai)
        {
            base.AddObject("Loais", loai);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuanTris EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuanTris(QuanTri quanTri)
        {
            base.AddObject("QuanTris", quanTri);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SalePromotions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSalePromotions(SalePromotion salePromotion)
        {
            base.AddObject("SalePromotions", salePromotion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SanPhams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSanPhams(SanPham sanPham)
        {
            base.AddObject("SanPhams", sanPham);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SanPhamHinhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSanPhamHinhs(SanPhamHinh sanPhamHinh)
        {
            base.AddObject("SanPhamHinhs", sanPhamHinh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ThuongHieux EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThuongHieux(ThuongHieu thuongHieu)
        {
            base.AddObject("ThuongHieux", thuongHieu);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="DonHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DonHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DonHang object.
        /// </summary>
        /// <param name="donHangID">Initial value of the DonHangID property.</param>
        /// <param name="ngayDatHang">Initial value of the NgayDatHang property.</param>
        /// <param name="tinhtrang">Initial value of the Tinhtrang property.</param>
        public static DonHang CreateDonHang(global::System.Int32 donHangID, global::System.DateTime ngayDatHang, global::System.Boolean tinhtrang)
        {
            DonHang donHang = new DonHang();
            donHang.DonHangID = donHangID;
            donHang.NgayDatHang = ngayDatHang;
            donHang.Tinhtrang = tinhtrang;
            return donHang;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DonHangID
        {
            get
            {
                return _DonHangID;
            }
            set
            {
                if (_DonHangID != value)
                {
                    OnDonHangIDChanging(value);
                    ReportPropertyChanging("DonHangID");
                    _DonHangID = StructuralObject.SetValidValue(value, "DonHangID");
                    ReportPropertyChanged("DonHangID");
                    OnDonHangIDChanged();
                }
            }
        }
        private global::System.Int32 _DonHangID;
        partial void OnDonHangIDChanging(global::System.Int32 value);
        partial void OnDonHangIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayDatHang
        {
            get
            {
                return _NgayDatHang;
            }
            set
            {
                OnNgayDatHangChanging(value);
                ReportPropertyChanging("NgayDatHang");
                _NgayDatHang = StructuralObject.SetValidValue(value, "NgayDatHang");
                ReportPropertyChanged("NgayDatHang");
                OnNgayDatHangChanged();
            }
        }
        private global::System.DateTime _NgayDatHang;
        partial void OnNgayDatHangChanging(global::System.DateTime value);
        partial void OnNgayDatHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKhachHang
        {
            get
            {
                return _TenKhachHang;
            }
            set
            {
                OnTenKhachHangChanging(value);
                ReportPropertyChanging("TenKhachHang");
                _TenKhachHang = StructuralObject.SetValidValue(value, true, "TenKhachHang");
                ReportPropertyChanged("TenKhachHang");
                OnTenKhachHangChanged();
            }
        }
        private global::System.String _TenKhachHang;
        partial void OnTenKhachHangChanging(global::System.String value);
        partial void OnTenKhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true, "DiaChi");
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value, true, "SoDienThoai");
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private global::System.String _SoDienThoai;
        partial void OnSoDienThoaiChanging(global::System.String value);
        partial void OnSoDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true, "GhiChu");
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Tinhtrang
        {
            get
            {
                return _Tinhtrang;
            }
            set
            {
                OnTinhtrangChanging(value);
                ReportPropertyChanging("Tinhtrang");
                _Tinhtrang = StructuralObject.SetValidValue(value, "Tinhtrang");
                ReportPropertyChanged("Tinhtrang");
                OnTinhtrangChanged();
            }
        }
        private global::System.Boolean _Tinhtrang;
        partial void OnTinhtrangChanging(global::System.Boolean value);
        partial void OnTinhtrangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="DonHangChiTiet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DonHangChiTiet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DonHangChiTiet object.
        /// </summary>
        /// <param name="donHangID">Initial value of the DonHangID property.</param>
        /// <param name="sanPhamID">Initial value of the SanPhamID property.</param>
        /// <param name="soLuong">Initial value of the SoLuong property.</param>
        /// <param name="donGia">Initial value of the DonGia property.</param>
        /// <param name="thanhTien">Initial value of the ThanhTien property.</param>
        public static DonHangChiTiet CreateDonHangChiTiet(global::System.Int32 donHangID, global::System.Int32 sanPhamID, global::System.Int32 soLuong, global::System.Decimal donGia, global::System.Decimal thanhTien)
        {
            DonHangChiTiet donHangChiTiet = new DonHangChiTiet();
            donHangChiTiet.DonHangID = donHangID;
            donHangChiTiet.SanPhamID = sanPhamID;
            donHangChiTiet.SoLuong = soLuong;
            donHangChiTiet.DonGia = donGia;
            donHangChiTiet.ThanhTien = thanhTien;
            return donHangChiTiet;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DonHangID
        {
            get
            {
                return _DonHangID;
            }
            set
            {
                if (_DonHangID != value)
                {
                    OnDonHangIDChanging(value);
                    ReportPropertyChanging("DonHangID");
                    _DonHangID = StructuralObject.SetValidValue(value, "DonHangID");
                    ReportPropertyChanged("DonHangID");
                    OnDonHangIDChanged();
                }
            }
        }
        private global::System.Int32 _DonHangID;
        partial void OnDonHangIDChanging(global::System.Int32 value);
        partial void OnDonHangIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SanPhamID
        {
            get
            {
                return _SanPhamID;
            }
            set
            {
                if (_SanPhamID != value)
                {
                    OnSanPhamIDChanging(value);
                    ReportPropertyChanging("SanPhamID");
                    _SanPhamID = StructuralObject.SetValidValue(value, "SanPhamID");
                    ReportPropertyChanged("SanPhamID");
                    OnSanPhamIDChanged();
                }
            }
        }
        private global::System.Int32 _SanPhamID;
        partial void OnSanPhamIDChanging(global::System.Int32 value);
        partial void OnSanPhamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SoLuong
        {
            get
            {
                return _SoLuong;
            }
            set
            {
                OnSoLuongChanging(value);
                ReportPropertyChanging("SoLuong");
                _SoLuong = StructuralObject.SetValidValue(value, "SoLuong");
                ReportPropertyChanged("SoLuong");
                OnSoLuongChanged();
            }
        }
        private global::System.Int32 _SoLuong;
        partial void OnSoLuongChanging(global::System.Int32 value);
        partial void OnSoLuongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DonGia
        {
            get
            {
                return _DonGia;
            }
            set
            {
                OnDonGiaChanging(value);
                ReportPropertyChanging("DonGia");
                _DonGia = StructuralObject.SetValidValue(value, "DonGia");
                ReportPropertyChanged("DonGia");
                OnDonGiaChanged();
            }
        }
        private global::System.Decimal _DonGia;
        partial void OnDonGiaChanging(global::System.Decimal value);
        partial void OnDonGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ThanhTien
        {
            get
            {
                return _ThanhTien;
            }
            set
            {
                OnThanhTienChanging(value);
                ReportPropertyChanging("ThanhTien");
                _ThanhTien = StructuralObject.SetValidValue(value, "ThanhTien");
                ReportPropertyChanged("ThanhTien");
                OnThanhTienChanged();
            }
        }
        private global::System.Decimal _ThanhTien;
        partial void OnThanhTienChanging(global::System.Decimal value);
        partial void OnThanhTienChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="KhuyenMai")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhuyenMai : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhuyenMai object.
        /// </summary>
        /// <param name="khuyenMaiID">Initial value of the KhuyenMaiID property.</param>
        /// <param name="ngayBatDau">Initial value of the NgayBatDau property.</param>
        /// <param name="ngayKetThuc">Initial value of the NgayKetThuc property.</param>
        /// <param name="giamGia">Initial value of the GiamGia property.</param>
        public static KhuyenMai CreateKhuyenMai(global::System.Int32 khuyenMaiID, global::System.DateTime ngayBatDau, global::System.DateTime ngayKetThuc, global::System.Double giamGia)
        {
            KhuyenMai khuyenMai = new KhuyenMai();
            khuyenMai.KhuyenMaiID = khuyenMaiID;
            khuyenMai.NgayBatDau = ngayBatDau;
            khuyenMai.NgayKetThuc = ngayKetThuc;
            khuyenMai.GiamGia = giamGia;
            return khuyenMai;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KhuyenMaiID
        {
            get
            {
                return _KhuyenMaiID;
            }
            set
            {
                if (_KhuyenMaiID != value)
                {
                    OnKhuyenMaiIDChanging(value);
                    ReportPropertyChanging("KhuyenMaiID");
                    _KhuyenMaiID = StructuralObject.SetValidValue(value, "KhuyenMaiID");
                    ReportPropertyChanged("KhuyenMaiID");
                    OnKhuyenMaiIDChanged();
                }
            }
        }
        private global::System.Int32 _KhuyenMaiID;
        partial void OnKhuyenMaiIDChanging(global::System.Int32 value);
        partial void OnKhuyenMaiIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ten
        {
            get
            {
                return _Ten;
            }
            set
            {
                OnTenChanging(value);
                ReportPropertyChanging("Ten");
                _Ten = StructuralObject.SetValidValue(value, true, "Ten");
                ReportPropertyChanged("Ten");
                OnTenChanged();
            }
        }
        private global::System.String _Ten;
        partial void OnTenChanging(global::System.String value);
        partial void OnTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayBatDau
        {
            get
            {
                return _NgayBatDau;
            }
            set
            {
                OnNgayBatDauChanging(value);
                ReportPropertyChanging("NgayBatDau");
                _NgayBatDau = StructuralObject.SetValidValue(value, "NgayBatDau");
                ReportPropertyChanged("NgayBatDau");
                OnNgayBatDauChanged();
            }
        }
        private global::System.DateTime _NgayBatDau;
        partial void OnNgayBatDauChanging(global::System.DateTime value);
        partial void OnNgayBatDauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayKetThuc
        {
            get
            {
                return _NgayKetThuc;
            }
            set
            {
                OnNgayKetThucChanging(value);
                ReportPropertyChanging("NgayKetThuc");
                _NgayKetThuc = StructuralObject.SetValidValue(value, "NgayKetThuc");
                ReportPropertyChanged("NgayKetThuc");
                OnNgayKetThucChanged();
            }
        }
        private global::System.DateTime _NgayKetThuc;
        partial void OnNgayKetThucChanging(global::System.DateTime value);
        partial void OnNgayKetThucChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mota
        {
            get
            {
                return _Mota;
            }
            set
            {
                OnMotaChanging(value);
                ReportPropertyChanging("Mota");
                _Mota = StructuralObject.SetValidValue(value, true, "Mota");
                ReportPropertyChanged("Mota");
                OnMotaChanged();
            }
        }
        private global::System.String _Mota;
        partial void OnMotaChanging(global::System.String value);
        partial void OnMotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double GiamGia
        {
            get
            {
                return _GiamGia;
            }
            set
            {
                OnGiamGiaChanging(value);
                ReportPropertyChanging("GiamGia");
                _GiamGia = StructuralObject.SetValidValue(value, "GiamGia");
                ReportPropertyChanged("GiamGia");
                OnGiamGiaChanged();
            }
        }
        private global::System.Double _GiamGia;
        partial void OnGiamGiaChanging(global::System.Double value);
        partial void OnGiamGiaChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="Loai")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Loai : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Loai object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Loai CreateLoai(global::System.Int32 id)
        {
            Loai loai = new Loai();
            loai.ID = id;
            return loai;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ten
        {
            get
            {
                return _Ten;
            }
            set
            {
                OnTenChanging(value);
                ReportPropertyChanging("Ten");
                _Ten = StructuralObject.SetValidValue(value, true, "Ten");
                ReportPropertyChanged("Ten");
                OnTenChanged();
            }
        }
        private global::System.String _Ten;
        partial void OnTenChanging(global::System.String value);
        partial void OnTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ChungLoaiID
        {
            get
            {
                return _ChungLoaiID;
            }
            set
            {
                OnChungLoaiIDChanging(value);
                ReportPropertyChanging("ChungLoaiID");
                _ChungLoaiID = StructuralObject.SetValidValue(value, "ChungLoaiID");
                ReportPropertyChanged("ChungLoaiID");
                OnChungLoaiIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ChungLoaiID;
        partial void OnChungLoaiIDChanging(Nullable<global::System.Int32> value);
        partial void OnChungLoaiIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEO
        {
            get
            {
                return _SEO;
            }
            set
            {
                OnSEOChanging(value);
                ReportPropertyChanging("SEO");
                _SEO = StructuralObject.SetValidValue(value, true, "SEO");
                ReportPropertyChanged("SEO");
                OnSEOChanged();
            }
        }
        private global::System.String _SEO;
        partial void OnSEOChanging(global::System.String value);
        partial void OnSEOChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="QuanTri")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuanTri : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuanTri object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static QuanTri CreateQuanTri(global::System.Int32 id)
        {
            QuanTri quanTri = new QuanTri();
            quanTri.ID = id;
            return quanTri;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true, "Username");
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TrangThai
        {
            get
            {
                return _TrangThai;
            }
            set
            {
                OnTrangThaiChanging(value);
                ReportPropertyChanging("TrangThai");
                _TrangThai = StructuralObject.SetValidValue(value, "TrangThai");
                ReportPropertyChanged("TrangThai");
                OnTrangThaiChanged();
            }
        }
        private Nullable<global::System.Boolean> _TrangThai;
        partial void OnTrangThaiChanging(Nullable<global::System.Boolean> value);
        partial void OnTrangThaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ten
        {
            get
            {
                return _Ten;
            }
            set
            {
                OnTenChanging(value);
                ReportPropertyChanging("Ten");
                _Ten = StructuralObject.SetValidValue(value, true, "Ten");
                ReportPropertyChanged("Ten");
                OnTenChanged();
            }
        }
        private global::System.String _Ten;
        partial void OnTenChanging(global::System.String value);
        partial void OnTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true, "DiaChi");
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sdt
        {
            get
            {
                return _Sdt;
            }
            set
            {
                OnSdtChanging(value);
                ReportPropertyChanging("Sdt");
                _Sdt = StructuralObject.SetValidValue(value, true, "Sdt");
                ReportPropertyChanged("Sdt");
                OnSdtChanged();
            }
        }
        private global::System.String _Sdt;
        partial void OnSdtChanging(global::System.String value);
        partial void OnSdtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value, "Level");
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private Nullable<global::System.Byte> _Level;
        partial void OnLevelChanging(Nullable<global::System.Byte> value);
        partial void OnLevelChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="SalePromotion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SalePromotion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SalePromotion object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static SalePromotion CreateSalePromotion(global::System.Int32 id)
        {
            SalePromotion salePromotion = new SalePromotion();
            salePromotion.ID = id;
            return salePromotion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ten
        {
            get
            {
                return _Ten;
            }
            set
            {
                OnTenChanging(value);
                ReportPropertyChanging("Ten");
                _Ten = StructuralObject.SetValidValue(value, true, "Ten");
                ReportPropertyChanged("Ten");
                OnTenChanged();
            }
        }
        private global::System.String _Ten;
        partial void OnTenChanging(global::System.String value);
        partial void OnTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] IDHinh
        {
            get
            {
                return StructuralObject.GetValidValue(_IDHinh);
            }
            set
            {
                OnIDHinhChanging(value);
                ReportPropertyChanging("IDHinh");
                _IDHinh = StructuralObject.SetValidValue(value, true, "IDHinh");
                ReportPropertyChanged("IDHinh");
                OnIDHinhChanged();
            }
        }
        private global::System.Byte[] _IDHinh;
        partial void OnIDHinhChanging(global::System.Byte[] value);
        partial void OnIDHinhChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="SanPham")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SanPham : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SanPham object.
        /// </summary>
        /// <param name="sanPhamID">Initial value of the SanPhamID property.</param>
        /// <param name="giaBan">Initial value of the GiaBan property.</param>
        /// <param name="ngayThem">Initial value of the NgayThem property.</param>
        public static SanPham CreateSanPham(global::System.Int32 sanPhamID, global::System.Decimal giaBan, global::System.DateTime ngayThem)
        {
            SanPham sanPham = new SanPham();
            sanPham.SanPhamID = sanPhamID;
            sanPham.GiaBan = giaBan;
            sanPham.NgayThem = ngayThem;
            return sanPham;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SanPhamID
        {
            get
            {
                return _SanPhamID;
            }
            set
            {
                if (_SanPhamID != value)
                {
                    OnSanPhamIDChanging(value);
                    ReportPropertyChanging("SanPhamID");
                    _SanPhamID = StructuralObject.SetValidValue(value, "SanPhamID");
                    ReportPropertyChanged("SanPhamID");
                    OnSanPhamIDChanged();
                }
            }
        }
        private global::System.Int32 _SanPhamID;
        partial void OnSanPhamIDChanging(global::System.Int32 value);
        partial void OnSanPhamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaSanPham
        {
            get
            {
                return _MaSanPham;
            }
            set
            {
                OnMaSanPhamChanging(value);
                ReportPropertyChanging("MaSanPham");
                _MaSanPham = StructuralObject.SetValidValue(value, true, "MaSanPham");
                ReportPropertyChanged("MaSanPham");
                OnMaSanPhamChanged();
            }
        }
        private global::System.String _MaSanPham;
        partial void OnMaSanPhamChanging(global::System.String value);
        partial void OnMaSanPhamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenSanPham
        {
            get
            {
                return _TenSanPham;
            }
            set
            {
                OnTenSanPhamChanging(value);
                ReportPropertyChanging("TenSanPham");
                _TenSanPham = StructuralObject.SetValidValue(value, true, "TenSanPham");
                ReportPropertyChanged("TenSanPham");
                OnTenSanPhamChanged();
            }
        }
        private global::System.String _TenSanPham;
        partial void OnTenSanPhamChanging(global::System.String value);
        partial void OnTenSanPhamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GiaBan
        {
            get
            {
                return _GiaBan;
            }
            set
            {
                OnGiaBanChanging(value);
                ReportPropertyChanging("GiaBan");
                _GiaBan = StructuralObject.SetValidValue(value, "GiaBan");
                ReportPropertyChanged("GiaBan");
                OnGiaBanChanged();
            }
        }
        private global::System.Decimal _GiaBan;
        partial void OnGiaBanChanging(global::System.Decimal value);
        partial void OnGiaBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> TrangThai
        {
            get
            {
                return _TrangThai;
            }
            set
            {
                OnTrangThaiChanging(value);
                ReportPropertyChanging("TrangThai");
                _TrangThai = StructuralObject.SetValidValue(value, "TrangThai");
                ReportPropertyChanged("TrangThai");
                OnTrangThaiChanged();
            }
        }
        private Nullable<global::System.Byte> _TrangThai;
        partial void OnTrangThaiChanging(Nullable<global::System.Byte> value);
        partial void OnTrangThaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mota
        {
            get
            {
                return _Mota;
            }
            set
            {
                OnMotaChanging(value);
                ReportPropertyChanging("Mota");
                _Mota = StructuralObject.SetValidValue(value, true, "Mota");
                ReportPropertyChanged("Mota");
                OnMotaChanged();
            }
        }
        private global::System.String _Mota;
        partial void OnMotaChanging(global::System.String value);
        partial void OnMotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDThuongHieu
        {
            get
            {
                return _IDThuongHieu;
            }
            set
            {
                OnIDThuongHieuChanging(value);
                ReportPropertyChanging("IDThuongHieu");
                _IDThuongHieu = StructuralObject.SetValidValue(value, "IDThuongHieu");
                ReportPropertyChanged("IDThuongHieu");
                OnIDThuongHieuChanged();
            }
        }
        private Nullable<global::System.Int32> _IDThuongHieu;
        partial void OnIDThuongHieuChanging(Nullable<global::System.Int32> value);
        partial void OnIDThuongHieuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDLoai
        {
            get
            {
                return _IDLoai;
            }
            set
            {
                OnIDLoaiChanging(value);
                ReportPropertyChanging("IDLoai");
                _IDLoai = StructuralObject.SetValidValue(value, "IDLoai");
                ReportPropertyChanged("IDLoai");
                OnIDLoaiChanged();
            }
        }
        private Nullable<global::System.Int32> _IDLoai;
        partial void OnIDLoaiChanging(Nullable<global::System.Int32> value);
        partial void OnIDLoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLanXem
        {
            get
            {
                return _SoLanXem;
            }
            set
            {
                OnSoLanXemChanging(value);
                ReportPropertyChanging("SoLanXem");
                _SoLanXem = StructuralObject.SetValidValue(value, "SoLanXem");
                ReportPropertyChanged("SoLanXem");
                OnSoLanXemChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLanXem;
        partial void OnSoLanXemChanging(Nullable<global::System.Int32> value);
        partial void OnSoLanXemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayThem
        {
            get
            {
                return _NgayThem;
            }
            set
            {
                OnNgayThemChanging(value);
                ReportPropertyChanging("NgayThem");
                _NgayThem = StructuralObject.SetValidValue(value, "NgayThem");
                ReportPropertyChanged("NgayThem");
                OnNgayThemChanged();
            }
        }
        private global::System.DateTime _NgayThem;
        partial void OnNgayThemChanging(global::System.DateTime value);
        partial void OnNgayThemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Promotion
        {
            get
            {
                return _Promotion;
            }
            set
            {
                OnPromotionChanging(value);
                ReportPropertyChanging("Promotion");
                _Promotion = StructuralObject.SetValidValue(value, "Promotion");
                ReportPropertyChanged("Promotion");
                OnPromotionChanged();
            }
        }
        private Nullable<global::System.Byte> _Promotion;
        partial void OnPromotionChanging(Nullable<global::System.Byte> value);
        partial void OnPromotionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDKhuyenMai
        {
            get
            {
                return _IDKhuyenMai;
            }
            set
            {
                OnIDKhuyenMaiChanging(value);
                ReportPropertyChanging("IDKhuyenMai");
                _IDKhuyenMai = StructuralObject.SetValidValue(value, "IDKhuyenMai");
                ReportPropertyChanged("IDKhuyenMai");
                OnIDKhuyenMaiChanged();
            }
        }
        private Nullable<global::System.Int32> _IDKhuyenMai;
        partial void OnIDKhuyenMaiChanging(Nullable<global::System.Int32> value);
        partial void OnIDKhuyenMaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEO
        {
            get
            {
                return _SEO;
            }
            set
            {
                OnSEOChanging(value);
                ReportPropertyChanging("SEO");
                _SEO = StructuralObject.SetValidValue(value, true, "SEO");
                ReportPropertyChanged("SEO");
                OnSEOChanged();
            }
        }
        private global::System.String _SEO;
        partial void OnSEOChanging(global::System.String value);
        partial void OnSEOChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShopMyPhamModel1", "FK_SanPhamHinh_SanPham", "SanPhamHinh")]
        public EntityCollection<SanPhamHinh> SanPhamHinhs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SanPhamHinh>("ShopMyPhamModel1.FK_SanPhamHinh_SanPham", "SanPhamHinh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SanPhamHinh>("ShopMyPhamModel1.FK_SanPhamHinh_SanPham", "SanPhamHinh", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="SanPhamHinh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SanPhamHinh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SanPhamHinh object.
        /// </summary>
        /// <param name="sanPhamHinhID">Initial value of the SanPhamHinhID property.</param>
        /// <param name="sanPhamID">Initial value of the SanPhamID property.</param>
        /// <param name="ngayThem">Initial value of the NgayThem property.</param>
        public static SanPhamHinh CreateSanPhamHinh(global::System.Int32 sanPhamHinhID, global::System.Int32 sanPhamID, global::System.DateTime ngayThem)
        {
            SanPhamHinh sanPhamHinh = new SanPhamHinh();
            sanPhamHinh.SanPhamHinhID = sanPhamHinhID;
            sanPhamHinh.SanPhamID = sanPhamID;
            sanPhamHinh.NgayThem = ngayThem;
            return sanPhamHinh;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SanPhamHinhID
        {
            get
            {
                return _SanPhamHinhID;
            }
            set
            {
                if (_SanPhamHinhID != value)
                {
                    OnSanPhamHinhIDChanging(value);
                    ReportPropertyChanging("SanPhamHinhID");
                    _SanPhamHinhID = StructuralObject.SetValidValue(value, "SanPhamHinhID");
                    ReportPropertyChanged("SanPhamHinhID");
                    OnSanPhamHinhIDChanged();
                }
            }
        }
        private global::System.Int32 _SanPhamHinhID;
        partial void OnSanPhamHinhIDChanging(global::System.Int32 value);
        partial void OnSanPhamHinhIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenHinh
        {
            get
            {
                return _TenHinh;
            }
            set
            {
                OnTenHinhChanging(value);
                ReportPropertyChanging("TenHinh");
                _TenHinh = StructuralObject.SetValidValue(value, true, "TenHinh");
                ReportPropertyChanged("TenHinh");
                OnTenHinhChanged();
            }
        }
        private global::System.String _TenHinh;
        partial void OnTenHinhChanging(global::System.String value);
        partial void OnTenHinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SanPhamID
        {
            get
            {
                return _SanPhamID;
            }
            set
            {
                OnSanPhamIDChanging(value);
                ReportPropertyChanging("SanPhamID");
                _SanPhamID = StructuralObject.SetValidValue(value, "SanPhamID");
                ReportPropertyChanged("SanPhamID");
                OnSanPhamIDChanged();
            }
        }
        private global::System.Int32 _SanPhamID;
        partial void OnSanPhamIDChanging(global::System.Int32 value);
        partial void OnSanPhamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> ThuTuHienThi
        {
            get
            {
                return _ThuTuHienThi;
            }
            set
            {
                OnThuTuHienThiChanging(value);
                ReportPropertyChanging("ThuTuHienThi");
                _ThuTuHienThi = StructuralObject.SetValidValue(value, "ThuTuHienThi");
                ReportPropertyChanged("ThuTuHienThi");
                OnThuTuHienThiChanged();
            }
        }
        private Nullable<global::System.Byte> _ThuTuHienThi;
        partial void OnThuTuHienThiChanging(Nullable<global::System.Byte> value);
        partial void OnThuTuHienThiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLanXem
        {
            get
            {
                return _SoLanXem;
            }
            set
            {
                OnSoLanXemChanging(value);
                ReportPropertyChanging("SoLanXem");
                _SoLanXem = StructuralObject.SetValidValue(value, "SoLanXem");
                ReportPropertyChanged("SoLanXem");
                OnSoLanXemChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLanXem;
        partial void OnSoLanXemChanging(Nullable<global::System.Int32> value);
        partial void OnSoLanXemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayThem
        {
            get
            {
                return _NgayThem;
            }
            set
            {
                OnNgayThemChanging(value);
                ReportPropertyChanging("NgayThem");
                _NgayThem = StructuralObject.SetValidValue(value, "NgayThem");
                ReportPropertyChanged("NgayThem");
                OnNgayThemChanged();
            }
        }
        private global::System.DateTime _NgayThem;
        partial void OnNgayThemChanging(global::System.DateTime value);
        partial void OnNgayThemChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShopMyPhamModel1", "FK_SanPhamHinh_SanPham", "SanPham")]
        public SanPham SanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("ShopMyPhamModel1.FK_SanPhamHinh_SanPham", "SanPham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("ShopMyPhamModel1.FK_SanPhamHinh_SanPham", "SanPham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SanPham> SanPhamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("ShopMyPhamModel1.FK_SanPhamHinh_SanPham", "SanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SanPham>("ShopMyPhamModel1.FK_SanPhamHinh_SanPham", "SanPham", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopMyPhamModel1", Name="ThuongHieu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ThuongHieu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ThuongHieu object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ThuongHieu CreateThuongHieu(global::System.Int32 id)
        {
            ThuongHieu thuongHieu = new ThuongHieu();
            thuongHieu.ID = id;
            return thuongHieu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTH
        {
            get
            {
                return _TenTH;
            }
            set
            {
                OnTenTHChanging(value);
                ReportPropertyChanging("TenTH");
                _TenTH = StructuralObject.SetValidValue(value, true, "TenTH");
                ReportPropertyChanged("TenTH");
                OnTenTHChanged();
            }
        }
        private global::System.String _TenTH;
        partial void OnTenTHChanging(global::System.String value);
        partial void OnTenTHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HinhTH
        {
            get
            {
                return _HinhTH;
            }
            set
            {
                OnHinhTHChanging(value);
                ReportPropertyChanging("HinhTH");
                _HinhTH = StructuralObject.SetValidValue(value, true, "HinhTH");
                ReportPropertyChanged("HinhTH");
                OnHinhTHChanged();
            }
        }
        private global::System.String _HinhTH;
        partial void OnHinhTHChanging(global::System.String value);
        partial void OnHinhTHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEO
        {
            get
            {
                return _SEO;
            }
            set
            {
                OnSEOChanging(value);
                ReportPropertyChanging("SEO");
                _SEO = StructuralObject.SetValidValue(value, true, "SEO");
                ReportPropertyChanged("SEO");
                OnSEOChanged();
            }
        }
        private global::System.String _SEO;
        partial void OnSEOChanging(global::System.String value);
        partial void OnSEOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> TrangThai
        {
            get
            {
                return _TrangThai;
            }
            set
            {
                OnTrangThaiChanging(value);
                ReportPropertyChanging("TrangThai");
                _TrangThai = StructuralObject.SetValidValue(value, "TrangThai");
                ReportPropertyChanged("TrangThai");
                OnTrangThaiChanged();
            }
        }
        private Nullable<global::System.Byte> _TrangThai;
        partial void OnTrangThaiChanging(Nullable<global::System.Byte> value);
        partial void OnTrangThaiChanged();

        #endregion

    }

    #endregion

}
